import React, { useCallback, useState, useRef, useEffect } from "react";
import { StyleSheet, TouchableOpacity, FlatList, Text, View } from "react-native";
import * as Animatable from "react-native-animatable";
import { AntDesign } from '@expo/vector-icons';
import colors from '../colors';
import { AutocompleteDropdown } from 'react-native-autocomplete-dropdown'

export default function Search({ navigation }) {
    const [selectedItem, setSelectedItem] = useState(null);
    // console.log(selectedItem)

    const showDetail = (props) => {
        useEffect(() => {
            if(selectedItem != null)
            {
                navigation.navigate("Detail", {
                    name:selectedItem,
                })
            }
        }, [selectedItem]);
    }

    useEffect(() => {
        navigation.setOptions({
            headerLeft: () => (
                <TouchableOpacity
                    onPress={() => navigation.navigate("Home")}
                >
                    <AntDesign name="left" size={24} style={styles.backButton} />
                </TouchableOpacity>
            ),
            });
    }, [navigation]);

  return (
    <View style={styles.container}>
    <View style={styles.centercontainer}>
      <AutocompleteDropdown
        clearOnFocus={true}
        closeOnBlur={true}
        closeOnSubmit={false}
        // initialValue={{id: '0'}} // or just '2'
        onSelectItem={item => {
            item && setSelectedItem(item.title)
          }}
        onSubmit={showDetail()}
        inputContainerStyle={{
            borderRadius: 10,
            width: 380,
        }}
        textInputProps={{
            placeholder: '칵테일을 입력해보세요',
          }}
        dataSet={[
                {id: '1', title:'어스퀘이크(진)'},
                {id: '2', title:'아이디얼'},
                {id: '3', title:'푸른 산호초'},
                {id: '4', title:'아티'},
                {id: '5', title:'아비에이션'},
                {id: '6', title:'애피타이저'},
                {id: '7', title:'아베이'},
                {id: '8', title:'아마폴라'},
                {id: '9', title:'암스테르담'},
                {id: '10', title:'어라운드 더 월드'},
                {id: '11', title:'알래스카'},
                {id: '12', title:'알렉산더스 시스터'},
                {id: '13', title:'앰버 드림'},
                {id: '14', title:'위즐리 가든'},
                {id: '15', title:'웨스턴 로즈'},
                {id: '16', title:'에이 원'},
                {id: '17', title:'영광의 마티니'},
                {id: '18', title:'어텀 리브스'},
                {id: '19', title:'엔젤 페이스'},
                {id: '20', title:'오렌지 피즈'},
                {id: '21', title:'오렌지 블로섬'},
                {id: '22', title:'카지노'},
                {id: '23', title:'카페 드 도쿄'},
                {id: '24', title:'카페 드 파리'},
                {id: '25', title:'카린'},
                {id: '26', title:'카루소'},
                {id: '27', title:'키스 인 더 다크'},
                {id: '28', title:'깁슨'},
                {id: '29', title:'김렛'},
                {id: '30', title:'그린 드래건'},
                {id: '31', title:'교카'},
                {id: '32', title:'그린 알래스카'},
                {id: '33', title:'크로스 보'},
                {id: '34', title:'클로버 클럽'},
                {id: '35', title:'골든 스크루(진)'},
                {id: '36', title:'골든 돈'},
                {id: '37', title:'골든 슬리퍼'},
                {id: '38', title:'골든 피즈'},
                {id: '39', title:'콩카 도라'},
                {id: '40', title:'자자'},
                {id: '41', title:'사사미유키'},
                {id: '42', title:'사파이언 쿨'},
                {id: '43', title:'섬머 브리즈'},
                {id: '44', title:'제임스 본드 마티니'},
                {id: '45', title:'주얼 하우스'},
                {id: '46', title:'실버 주빌리'},
                {id: '47', title:'실버 스트리크'},
                {id: '48', title:'실버 피즈'},
                {id: '49', title:'실버 불릿'},
                {id: '50', title:'진 앤드 이트'},
                {id: '51', title:'진 앤드 비터스'},
                {id: '52', title:'진 칵테일'},
                {id: '53', title:'진 코블러'},
                {id: '54', title:'진 사워'},
                {id: '55', title:'진 슬링'},
                {id: '56', title:'진 데이지'},
                {id: '57', title:'진 토닉'},
                {id: '58', title:'진 벅'},
                {id: '59', title:'진 피즈'},
                {id: '60', title:'진 앤드 라임'},
                {id: '61', title:'싱가포르 슬링'},
                {id: '62', title:'스타더스트 리뷰'},
                {id: '63', title:'스카이 크루즈'},
                {id: '64', title:'스프링 오페라'},
                {id: '65', title:'스프링 버드'},
                {id: '66', title:'세븐스 헤븐 No 1'},
                {id: '67', title:'세븐스 헤븐 No 2'},
                {id: '68', title:'더비'},
                {id: '69', title:'다이너스티'},
                {id: '70', title:'탕카레 임페리얼'},
                {id: '71', title:'탕카레 퀸'},
                {id: '72', title:'탕카레 필드'},
                {id: '73', title:'탕카레 포레스트'},
                {id: '74', title:'탱고'},
                {id: '75', title:'D.O.M 칵테일'},
                {id: '76', title:'테이크 파이브'},
                {id: '77', title:'텍사스 피즈'},
                {id: '78', title:'듀 바리'},
                {id: '79', title:'듀보네'},
                {id: '80', title:'톰 콜린스'},
                {id: '81', title:'드라카르'},
                {id: '82', title:'네그로니'},
                {id: '83', title:'녹아웃'},
                {id: '84', title:'바텐더'},
                {id: '85', title:'퍼펙트 마티니'},
                {id: '86', title:'하이드 파크'},
                {id: '87', title:'파시모 레이디'},
                {id: '88', title:'버뮤다 로즈'},
                {id: '89', title:'파라다이스'},
                {id: '90', title:'파리지앵'},
                {id: '91', title:'하와이언'},
                {id: '92', title:'피카딜리 나이트'},
                {id: '93', title:'피카딜리 파크'},
                {id: '94', title:'핑크 진'},
                {id: '95', title:'핑크 레이디'},
                {id: '96', title:'판타지수타'},
                {id: '97', title:'피닉스 진 슬링'},
                {id: '98', title:'포른 엔젤'},
                {id: '99', title:'블러드 하운드'},
                {id: '100', title:'브리티시 마치'},
                {id: '101', title:'프린스턴'},
                {id: '102', title:'프린세스 메리'},
                {id: '103', title:'블루 문'},
                {id: '104', title:'불독 하이볼'},
                {id: '105', title:'프레셔스 하트'},
                {id: '106', title:'프렌치75'},
                {id: '107', title:'플로리다'},
                {id: '108', title:'브롱크스'},
                {id: '109', title:'버몬트'},
                {id: '110', title:'호놀룰루'},
                {id: '111', title:'호프만 하우스 피즈'},
                {id: '112', title:'화이트 레이디'},
                {id: '113', title:'화이트 로즈'},
                {id: '114', title:'마운트 후지'},
                {id: '115', title:'마그놀리아 블로섬'},
                {id: '116', title:'마티니'},
                {id: '117', title:'미스티'},
                {id: '118', title:'미스터리 서클'},
                {id: '119', title:'밀리언 달러'},
                {id: '120', title:'밀키 웨이'},
                {id: '121', title:'밀비'},
                {id: '122', title:'문 리버'},
                {id: '123', title:'메리 위도'},
                {id: '124', title:'멜론 스페셜'},
                {id: '125', title:'요코하마'},
                {id: '126', title:'라무스 진 피즈'},
                {id: '127', title:'리틀 위치'},
                {id: '128', title:'러시안'},
                {id: '129', title:'레드 스파클'},
                {id: '130', title:'레드 라이온'},
                {id: '131', title:'레이디 80'},
                {id: '132', title:'로열 스마일'},
                {id: '133', title:'로열 피즈'},
                {id: '134', title:'로열 로망스'},
                {id: '135', title:'로드스터'},
                {id: '136', title:'롱 아일랜드 아이스티'},
                {id: '137', title:'런던 아이'},
                {id: '138', title:'런던의 마녀'},
                {id: '139', title:'아쿠덕트'},
                {id: '140', title:'아프레 스키'},
                {id: '141', title:'안젤로'},
                {id: '142', title:'앰파이넨'},
                {id: '143', title:'이스트 윙'},
                {id: '144', title:'보드카 아이스버그'},
                {id: '145', title:'보드카 애플 주스'},
                {id: '146', title:'보드카 칵테일'},
                {id: '147', title:'보드카 깁슨'},
                {id: '148', title:'보드카 김렛'},
                {id: '149', title:'보드카 토닉'},
                {id: '150', title:'보드카 리키'},
                {id: '151', title:'보드카티니'},
                {id: '152', title:'S.W.I'},
                {id: '153', title:'엠 45'},
                {id: '154', title:'올드 잉글랜드'},
                {id: '155', title:'옴니아'},
                {id: '156', title:'카이피로스카'},
                {id: '157', title:'카운트 스토로가노프'},
                {id: '158', title:'카미카제'},
                {id: '159', title:'그루프 스트림'},
                {id: '160', title:'키스 오브 파이어'},
                {id: '161', title:'키시 로즈'},
                {id: '162', title:'키스 미'},
                {id: '163', title:'그랑프리'},
                {id: '164', title:'그린 판타지'},
                {id: '165', title:'그린 필드'},
                {id: '166', title:'크레치마'},
                {id: '167', title:'케이프 코더'},
                {id: '168', title:'골든 스크루(보드카)'},
                {id: '169', title:'골든 텅'},
                {id: '170', title:'코사크'},
                {id: '171', title:'코스모폴리탄'},
                {id: '172', title:'갓마더'},
                {id: '173', title:'콜로니'},
                {id: '174', title:'시 브리즈'},
                {id: '175', title:'짚시'},
                {id: '176', title:'실버 윙'},
                {id: '177', title:'스크루 드라이버'},
                {id: '178', title:'스트로베리 필즈'},
                {id: '179', title:'스노 플레이크'},
                {id: '180', title:'스매시'},
                {id: '181', title:'슬러지 해머'},
                {id: '182', title:'섹스 온 더 비치'},
                {id: '183', title:'소비에트'},
                {id: '184', title:'솔티 도그'},
                {id: '185', title:'턱시도'},
                {id: '186', title:'타와리시'},
                {id: '187', title:'치치'},
                {id: '188', title:'츠아리느'},
                {id: '189', title:'데로바드'},
                {id: '190', title:'트로이카'},
                {id: '191', title:'니노치카'},
                {id: '192', title:'바바라'},
                {id: '193', title:'바브드 와이어'},
                {id: '194', title:'하베이 월벙거'},
                {id: '195', title:'하이 라이프'},
                {id: '196', title:'바카라'},
                {id: '197', title:'패트리샤'},
                {id: '198', title:'파나세'},
                {id: '199', title:'바히네'},
                {id: '200', title:'발라라이카'},
                {id: '201', title:'벌루션'},
                {id: '202', title:'판타지아'},
                {id: '203', title:'페스트루스'},
                {id: '204', title:'피닉스'},
                {id: '205', title:'플라잉 그래스 호퍼'},
                {id: '206', title:'블랙 러시안'},
                {id: '207', title:'블랙 클라우드'},
                {id: '208', title:'블러디 시저'},
                {id: '209', title:'블러디 메리'},
                {id: '210', title:'블러디 블루'},
                {id: '211', title:'플라밍고'},
                {id: '212', title:'플라밍고 레이디'},
                {id: '213', title:'브루스터 스페셜'},
                {id: '214', title:'블루 먼데이'},
                {id: '215', title:'블루 라군'},
                {id: '216', title:'불 쇼트'},
                {id: '217', title:'불독'},
                {id: '218', title:'불렛'},
                {id: '219', title:'헤어 라이저'},
                {id: '220', title:'베르니스'},
                {id: '221', title:'볼가'},
                {id: '222', title:'볼가 보트만'},
                {id: '223', title:'폴로네이즈'},
                {id: '224', title:'화이트 스파이더'},
                {id: '225', title:'화이트 러시안'},
                {id: '226', title:'봄버'},
                {id: '227', title:'마카룬'},
                {id: '228', title:'머기 블루'},
                {id: '229', title:'머드 슬라이드'},
                {id: '230', title:'마릴린 먼로'},
                {id: '231', title:'멜론 볼'},
                {id: '232', title:'마루루'},
                {id: '233', title:'모스코 뮬'},
                {id: '234', title:'라일라'},
                {id: '235', title:'러시안'},
                {id: '236', title:'루나 파크'},
                {id: '237', title:'뤼팽'},
                {id: '238', title:'레이크 퀸'},
                {id: '239', title:'레드 애플'},
                {id: '240', title:'레드 립스'},
                {id: '241', title:'로열 브라이드'},
                {id: '242', title:'로열 러시안'},
                {id: '243', title:'로즈 오브 바르샤바'},
                {id: '244', title:'로드 런너'},
                {id: '245', title:'로베르타'},
                {id: '246', title:'바르샤바'},
                {id: '247', title:'아이 오프너'},
                {id: '248', title:'아카풀코'},
                {id: '249', title:'아스트로노트'},
                {id: '250', title:'아디오스 아미고스'},
                {id: '251', title:'아메리칸 플라이어'},
                {id: '252', title:'알디라'},
                {id: '253', title:'앙티르'},
                {id: '254', title:'이슬라 데 피노스'},
                {id: '255', title:'인디언 섬머'},
                {id: '256', title:'워털루'},
                {id: '257', title:'에스토릴81'},
                {id: '258', title:'엑스 와이 지'},
                {id: '259', title:'엘 자디네로'},
                {id: '260', title:'엘 조르잘'},
                {id: '261', title:'엘 프레지던트'},
                {id: '262', title:'오로라'},
                {id: '263', title:'카이피리냐'},
                {id: '264', title:'카사블랑카'},
                {id: '265', title:'카바리에리'},
                {id: '266', title:'카리비안 크루즈'},
                {id: '267', title:'쿠바 리브레'},
                {id: '268', title:'쿠반'},
                {id: '269', title:'킹스톤'},
                {id: '270', title:'쿼터 데크'},
                {id: '271', title:'그린 아이즈'},
                {id: '272', title:'그로그'},
                {id: '273', title:'골든 게이트'},
                {id: '274', title:'골든 플라잉'},
                {id: '275', title:'서드 레일'},
                {id: '276', title:'산티아고'},
                {id: '277', title:'샥스 투스 No 1'},
                {id: '278', title:'자메이카 조'},
                {id: '279', title:'상하이'},
                {id: '280', title:'실비아'},
                {id: '281', title:'스위트 메모리즈'},
                {id: '282', title:'스칼릿 레이디'},
                {id: '283', title:'스카이 다이빙'},
                {id: '284', title:'스콜피온'},
                {id: '285', title:'스탄레이'},
                {id: '286', title:'스트로베리 팜'},
                {id: '287', title:'스페니시 타운'},
                {id: '288', title:'셉템버 몬'},
                {id: '289', title:'소노라'},
                {id: '290', title:'좀비'},
                {id: '291', title:'다이키리'},
                {id: '292', title:'차이니스 이치'},
                {id: '293', title:'톰&제리'},
                {id: '294', title:'드래곤 레이디'},
                {id: '295', title:'트로피컬 이치'},
                {id: '296', title:'트로피컬 미모사'},
                {id: '297', title:'트로픽 오브 카프리콘'},
                {id: '298', title:'트와이라이트 존'},
                {id: '299', title:'니커보커 스페셜'},
                {id: '300', title:'네이키드 레이디'},
                {id: '301', title:'네바다'},
                {id: '302', title:'파인애플 피즈'},
                {id: '303', title:'바카르디아노'},
                {id: '304', title:'바카르디'},
                {id: '305', title:'허니 서클'},
                {id: '306', title:'하바나 비치'},
                {id: '307', title:'바하마'},
                {id: '308', title:'바히아'},
                {id: '309', title:'바라쿠다'},
                {id: '310', title:'비너스'},
                {id: '311', title:'피냐 콜라다'},
                {id: '312', title:'프티트 플루어르'},
                {id: '313', title:'플래티넘 블론드'},
                {id: '314', title:'블랙 로즈'},
                {id: '315', title:'플랜터스 칵테일'},
                {id: '316', title:'플랜터스 펀치'},
                {id: '317', title:'블루 하와이'},
                {id: '318', title:'블루 하와이안'},
                {id: '319', title:'프로즌 다이키리'},
                {id: '320', title:'프로즌 파인애플 다이키리'},
                {id: '321', title:'프로즌 바나나 다이키리'},
                {id: '322', title:'프로즌 민트 다이키리'},
                {id: '323', title:'폴라 쇼트 컷'},
                {id: '324', title:'보스턴 쿨러'},
                {id: '325', title:'핫 에그노그'},
                {id: '326', title:'하 버터드 럼'},
                {id: '327', title:'마이 마미'},
                {id: '328', title:'마이애미'},
                {id: '329', title:'마이타이'},
                {id: '330', title:'마우이 피즈'},
                {id: '331', title:'마야'},
                {id: '332', title:'밀리오네어'},
                {id: '333', title:'뭄바'},
                {id: '334', title:'무카로'},
                {id: '335', title:'메리 피크포드'},
                {id: '336', title:'모히토'},
                {id: '337', title:'럼 오렌지'},
                {id: '338', title:'럼 쿨러'},
                {id: '339', title:'럼 콜린스'},
                {id: '340', title:'럼 사워'},
                {id: '341', title:'럼 쥴럽'},
                {id: '342', title:'럼 듀보네'},
                {id: '343', title:'럼 피즈'},
                {id: '344', title:'럼 플로트'},
                {id: '345', title:'리콜리아노'},
                {id: '346', title:'리틀 프린세스'},
                {id: '347', title:'로열 코코 펀치'},
                {id: '348', title:'와라탐'},
                {id: '349', title:'애틀랜틱 코냑'},
                {id: '350', title:'애프터눈'},
                {id: '351', title:'아메리칸 뷰티'},
                {id: '352', title:'아라고'},
                {id: '353', title:'알렉산더'},
                {id: '354', title:'암브로시아'},
                {id: '355', title:'예스 앤드 노'},
                {id: '356', title:'이스트 인디아 No 1'},
                {id: '357', title:'이스트 인디아'},
                {id: '358', title:'인터내셔널'},
                {id: '359', title:'위프 노모어'},
                {id: '360', title:'위치 웨이'},
                {id: '361', title:'윌리 스미스'},
                {id: '362', title:'에스키모'},
                {id: '363', title:'애피큐리안'},
                {id: '364', title:'오드 매킨타이어'},
                {id: '365', title:'엘리스'},
                {id: '366', title:'올림픽'},
                {id: '367', title:'카카투즈'},
                {id: '368', title:'가제트'},
                {id: '369', title:'칼리메로'},
                {id: '370', title:'카르나발'},
                {id: '371', title:'키스 프롬 헤븐'},
                {id: '372', title:'캐롤'},
                {id: '373', title:'퀸 엘리자베스'},
                {id: '374', title:'퀵클리'},
                {id: '375', title:'퀘이커스'},
                {id: '376', title:'클래식'},
                {id: '377', title:'그린 룸'},
                {id: '378', title:'크리스'},
                {id: '379', title:'케르비'},
                {id: '380', title:'코프스 리바이버 No 1'},
                {id: '381', title:'코프스 리바이버 No 4'},
                {id: '382', title:'골든 메달리온'},
                {id: '383', title:'골든 글림'},
                {id: '384', title:'콜드 데크'},
                {id: '385', title:'코냑 오렌지'},
                {id: '386', title:'코냑 칵테일'},
                {id: '387', title:'서 월터'},
                {id: '388', title:'사이드카'},
                {id: '389', title:'서머 펀'},
                {id: '390', title:'사라토가'},
                {id: '391', title:'선더 클랩'},
                {id: '392', title:'시카고'},
                {id: '393', title:'시티 슬리커'},
                {id: '394', title:'저지 라이트닝'},
                {id: '395', title:'샹제리제'},
                {id: '396', title:'샴페인 쿨러'},
                {id: '397', title:'스위트 에덴'},
                {id: '398', title:'줌'},
                {id: '399', title:'스쿠프'},
                {id: '400', title:'스팅어'},
                {id: '401', title:'슬램 No 2'},
                {id: '402', title:'스페셜 라프'},
                {id: '403', title:'스리 밀러'},
                {id: '404', title:'슬러지 해머'},
                {id: '405', title:'슬로피 조'},
                {id: '406', title:'스완 송'},
                {id: '407', title:'다이나마이트(브랜디)'},
                {id: '408', title:'더블 트러블'},
                {id: '409', title:'던힐71'},
                {id: '410', title:'찰스'},
                {id: '411', title:'초콜릿 솔저'},
                {id: '412', title:'티엔티'},
                {id: '413', title:'데이비스 브랜디'},
                {id: '414', title:'댑스 봄'},
                {id: '415', title:'토퍼'},
                {id: '416', title:'톱스 스마일'},
                {id: '417', title:'드림'},
                {id: '418', title:'나이트캡'},
                {id: '419', title:'낸시'},
                {id: '420', title:'니콜라시카'},
                {id: '421', title:'닉스 온'},
                {id: '422', title:'뉴튼스 스페셜'},
                {id: '423', title:'허큘리스'},
                {id: '424', title:'하바드'},
                {id: '425', title:'패신저 리스트'},
                {id: '426', title:'반더빌트'},
                {id: '427', title:'피터 타워'},
                {id: '428', title:'빅보이'},
                {id: '429', title:'비트윈 더 시츠'},
                {id: '430', title:'빌리 해밀턴'},
                {id: '431', title:'판타지오'},
                {id: '432', title:'피비 스노'},
                {id: '433', title:'후플라'},
                {id: '434', title:'페이버리트'},
                {id: '435', title:'페르네'},
                {id: '436', title:'포 스코어'},
                {id: '437', title:'브랜디 칵테일'},
                {id: '438', title:'브랜디 에그 노그'},
                {id: '439', title:'브랜디 건프'},
                {id: '440', title:'브랜드 크러스타'},
                {id: '441', title:'브랜드 콜린스'},
                {id: '442', title:'브랜드 샴파렐'},
                {id: '443', title:'브랜디 픽스'},
                {id: '444', title:'프린스 찰스'},
                {id: '445', title:'블 프로그'},
                {id: '446', title:'플레이메이트'},
                {id: '447', title:'프레스토'},
                {id: '448', title:'프렌치 커넥션'},
                {id: '449', title:'프루프'},
                {id: '450', title:'베티 로스'},
                {id: '451', title:'베네딕틴 칵테일'},
                {id: '452', title:'베란다'},
                {id: '453', title:'펭귄'},
                {id: '454', title:'휘프'},
                {id: '455', title:'호스 넥'},
                {id: '456', title:'버튼 훅'},
                {id: '457', title:'보니 프린스'},
                {id: '458', title:'화이 메리'},
                {id: '459', title:'봄베이'},
                {id: '460', title:'미카도'},
                {id: '461', title:'물랭 로즈'},
                {id: '462', title:'문 레이커'},
                {id: '463', title:'메트로폴리탄 No 1'},
                {id: '464', title:'메트로폴리탄 No 2'},
                {id: '465', title:'모닝'},
                {id: '466', title:'몬태나'},
                {id: '467', title:'영맨'},
                {id: '468', title:'라 홀라'},
                {id: '469', title:'리에종'},
                {id: '470', title:'릴리안'},
                {id: '471', title:'릴리퍼트'},
                {id: '472', title:'레이 롱'},
                {id: '473', title:'레이크 사이드'},
                {id: '474', title:'레이디 오브 메이'},
                {id: '475', title:'레이디 비 굿'},
                {id: '476', title:'라우드스피커'},
                {id: '477', title:'롤스 로이스'},
                {id: '478', title:'로스 로열'},
                {id: '479', title:'업 투 데이트'},
                {id: '480', title:'어드미럴'},
                {id: '481', title:'아이리시 커피'},
                {id: '482', title:'아피니티'},
                {id: '483', title:'앨곤킨'},
                {id: '484', title:'알폰소 카포네'},
                {id: '485', title:'언터처블'},
                {id: '486', title:'비발레오'},
                {id: '487', title:'위즈 뱅'},
                {id: '488', title:'위스키 온 더 록'},
                {id: '489', title:'위스키 칵테일'},
                {id: '490', title:'위스키 코블러'},
                {id: '491', title:'위스키 사워'},
                {id: '492', title:'위스키 토디'},
                {id: '493', title:'위스티 소다'},
                {id: '494', title:'위스키 맥'},
                {id: '495', title:'위스키 플로트'},
                {id: '496', title:'위스키 미스트'},
                {id: '497', title:'H.B.C 칵테일'},
                {id: '498', title:'에반스'},
                {id: '499', title:'에리카'},
                {id: '500', title:'엠버시 로열'},
                {id: '501', title:'올드 니크'},
                {id: '502', title:'올드 펄'},
                {id: '503', title:'올드 패션드'},
                {id: '504', title:'오리엔탈'},
                {id: '505', title:'오를레아니안'},
                {id: '506', title:'카우보이'},
                {id: '507', title:'키스 미 퀵'},
                {id: '508', title:'캡틴 콜린스'},
                {id: '509', title:'킹 조지 피브스'},
                {id: '510', title:'킹스 밸리'},
                {id: '511', title:'클로버 나이트'},
                {id: '512', title:'클론다이크 쿨러'},
                {id: '513', title:'케이블그램 하이볼'},
                {id: '514', title:'캔터키 커늘'},
                {id: '515', title:'코튼 플라워'},
                {id: '516', title:'갓파더'},
                {id: '517', title:'코모도르'},
                {id: '518', title:'사일런트 서드'},
                {id: '519', title:'서던 진저'},
                {id: '520', title:'서던 벨르'},
                {id: '521', title:'서머 히스'},
                {id: '522', title:'존 콜린스'},
                {id: '523', title:'스카치 킬트'},
                {id: '524', title:'스카치 콜린스'},
                {id: '525', title:'스카치 프라페'},
                {id: '526', title:'세인트 앤드류스'},
                {id: '527', title:'타탄 체크'},
                {id: '528', title:'더비 피즈'},
                {id: '529', title:'처칠'},
                {id: '530', title:'데일리 메일'},
                {id: '531', title:'테네시 쿨러'},
                {id: '532', title:'나이트 세이드'},
                {id: '533', title:'뉴욕'},
                {id: '534', title:'네빈스'},
                {id: '535', title:'바바리 코스트'},
                {id: '536', title:'바비칸'},
                {id: '537', title:'퍼펙트 로브 로이'},
                {id: '538', title:'버번 쿨러'},
                {id: '539', title:'버버넬라'},
                {id: '540', title:'버번 콜린스'},
                {id: '541', title:'버번 미스트'},
                {id: '542', title:'하이 해트'},
                {id: '543', title:'하이볼'},
                {id: '544', title:'하이랜드 쿨러'},
                {id: '545', title:'파디'},
                {id: '546', title:'해리 로더'},
                {id: '547', title:'허리케인'},
                {id: '548', title:'팬 아메리칸'},
                {id: '549', title:'포리브스 클로버'},
                {id: '550', title:'헌터'},
                {id: '551', title:'블랙 호크'},
                {id: '552', title:'블랙 워치'},
                {id: '553', title:'블러드 앤드 샌드'},
                {id: '554', title:'브루클린'},
                {id: '555', title:'버보넬라'},
                {id: '556', title:'프로즌 스카치'},
                {id: '557', title:'헤어 오브 더 독'},
                {id: '558', title:'베네딕트'},
                {id: '559', title:'홀 인 원'},
                {id: '560', title:'핫 위스키 토디'},
                {id: '561', title:'마이애미 비치'},
                {id: '562', title:'마이 도쿄'},
                {id: '563', title:'마미 테일러'},
                {id: '564', title:'맨해튼'},
                {id: '565', title:'민트 쿨러'},
                {id: '566', title:'멜팅'},
                {id: '567', title:'민트 쥴렙'},
                {id: '568', title:'라이 앤드 드라이'},
                {id: '569', title:'모닝 글로리 피즈'},
                {id: '570', title:'라이 위스키 칵테일'},
                {id: '571', title:'라이 콜린스'},
                {id: '572', title:'라이 레인'},
                {id: '573', title:'러스티 네일'},
                {id: '574', title:'린스티드'},
                {id: '575', title:'레이디스'},
                {id: '576', title:'레이디스 드림'},
                {id: '577', title:'록 로몬드'},
                {id: '578', title:'로스엔젤레스'},
                {id: '579', title:'로버트 번즈'},
                {id: '580', title:'로열 앰베세더'},
                {id: '581', title:'로브 로이'},
                {id: '582', title:'워드 에이트'},
                {id: '583', title:'원 아일랜드'},
                {id: '584', title:'아이스 브레이커'},
                {id: '585', title:'아카풀코'},
                {id: '586', title:'아카풀코 골드'},
                {id: '587', title:'어스퀘이크(데킬라)'},
                {id: '588', title:'아즈테카'},
                {id: '589', title:'아메리칸 리전 마르가리타'},
                {id: '590', title:'앰베서더'},
                {id: '591', title:'에버 그린'},
                {id: '592', title:'엘 디아블로'},
                {id: '593', title:'코코넛 데킬라'},
                {id: '594', title:'콘치타'},
                {id: '595', title:'실크 스타킹'},
                {id: '596', title:'시클라멘'},
                {id: '597', title:'슬로 데킬라'},
                {id: '598', title:'차파라'},
                {id: '599', title:'데킬라 앤드 토닉'},
                {id: '600', title:'테키니'},
                {id: '601', title:'데킬라 아 라 멕시칸'},
                {id: '602', title:'데킬라 오렌지'},
                {id: '603', title:'데킬라 칵테일'},
                {id: '604', title:'데킬라 선셋'},
                {id: '605', title:'데킬라 선라이즈'},
                {id: '606', title:'데킬라 데이지'},
                {id: '607', title:'두랑고'},
                {id: '608', title:'판초 빌라'},
                {id: '609', title:'피카도르'},
                {id: '610', title:'블러디 불'},
                {id: '611', title:'프로스트바이트'},
                {id: '612', title:'프로즌 스트로베리'},
                {id: '613', title:'프로즌 블루 마가리타'},
                {id: '614', title:'브로드웨이 서스트'},
                {id: '615', title:'헤르메스'},
                {id: '616', title:'마타도르'},
                {id: '617', title:'마리아 데레사'},
                {id: '618', title:'마르가리타'},
                {id: '619', title:'멕시칸'},
                {id: '620', title:'머킹버드'},
                {id: '621', title:'라이징 선'},
                {id: '622', title:'아도니스'},
                {id: '623', title:'아딩톤'},
                {id: '624', title:'아무르'},
                {id: '625', title:'아메리카노'},
                {id: '626', title:'아메리칸 레모네이드'},
                {id: '627', title:'위스턴 일렉트릭'},
                {id: '628', title:'키르'},
                {id: '629', title:'키르 로열'},
                {id: '630', title:'클라우드 버스터'},
                {id: '631', title:'코로네이션'},
                {id: '632', title:'쉐리 트위스트'},
                {id: '633', title:'쉐리 플립'},
                {id: '634', title:'주얼리 박스'},
                {id: '635', title:'샴페인 칵테일'},
                {id: '636', title:'샴페인 쥴렙'},
                {id: '637', title:'심포니'},
                {id: '638', title:'스프리처'},
                {id: '639', title:'스마일링'},
                {id: '640', title:'세레브레이션'},
                {id: '641', title:'솔 키스'},
                {id: '642', title:'다이나마이트(샴페인)'},
                {id: '643', title:'채플'},
                {id: '644', title:'버건디 칵테일'},
                {id: '645', title:'바르보타주'},
                {id: '646', title:'뱀부'},
                {id: '647', title:'피치 레이디'},
                {id: '648', title:'비숍'},
                {id: '649', title:'푸스 라피에르'},
                {id: '650', title:'블랙 앤드 탠'},
                {id: '651', title:'블랙 레인'},
                {id: '652', title:'블랙 펄'},
                {id: '653', title:'브로큰 스퍼'},
                {id: '654', title:'헤밍웨이'},
                {id: '655', title:'벨리니'},
                {id: '656', title:'베르무트 앤드 카시스'},
                {id: '657', title:'포트 플립'},
                {id: '658', title:'폼피에 데이지'},
                {id: '659', title:'미모사'},
                {id: '660', title:'루지타니아'},
                {id: '661', title:'레글론'},
                {id: '662', title:'로이 하워드'},
                {id: '663', title:'로열 하이네스'},
                {id: '664', title:'로즈'},
                {id: '665', title:'워싱턴'},
                {id: '666', title:'와인 쿨러'},
                {id: '667', title:'와인 코블러'},
                {id: '668', title:'애프터 디너'},
                {id: '669', title:'아프리콧 쿨러'},
                {id: '670', title:'옐로 패롯'},
                {id: '671', title:'위도우즈 키스'},
                {id: '672', title:'엔젤스 팁'},
                {id: '673', title:'카카오 피즈'},
                {id: '674', title:'칼루아&밀크'},
                {id: '675', title:'캄파리 오렌지'},
                {id: '676', title:'키스 미 퀵'},
                {id: '677', title:'쿠바 리브레 슈프림'},
                {id: '678', title:'키르슈 카시스'},
                {id: '679', title:'킹 알퐁소'},
                {id: '680', title:'퀸 마니에'},
                {id: '681', title:'쿨 바나나'},
                {id: '682', title:'그라스호퍼'},
                {id: '683', title:'글래드 아이'},
                {id: '684', title:'골든 캐딜락'},
                {id: '685', title:'삼부카 콘 모스카'},
                {id: '686', title:'스위트 하트'},
                {id: '687', title:'골든 드림'},
                {id: '688', title:'스위세스'},
                {id: '689', title:'스노 사로노'},
                {id: '690', title:'스노볼'},
                {id: '691', title:'스프모니'},
                {id: '692', title:'슬리퍼리 니플'},
                {id: '693', title:'슬로 진 피즈'},
                {id: '694', title:'체리 블로섬'},
                {id: '695', title:'찰리 채플린'},
                {id: '696', title:'토마토'},
                {id: '697', title:'나이트폴'},
                {id: '698', title:'하버드 쿨러'},
                {id: '699', title:'펄 브리지'},
                {id: '700', title:'바나나 브리스'},
                {id: '701', title:'바이올렛 피즈'},
                {id: '702', title:'파파게나'},
                {id: '703', title:'발렌시아'},
                {id: '704', title:'피콘 앤드 그레나덴'},
                {id: '705', title:'핑크 스콰렐'},
                {id: '706', title:'핑퐁'},
                {id: '707', title:'푸스 카페'},
                {id: '708', title:'페어리랜드'},
                {id: '709', title:'블루 레이디'},
                {id: '710', title:'프렐류드 피즈'},
                {id: '711', title:'벨벳 해머'},
                {id: '712', title:'페로케'},
                {id: '713', title:'화이트 사틴'},
                {id: '714', title:'민트 프라페'},
                {id: '715', title:'메리 위도 No 2'},
                {id: '716', title:'모레스크'},
                {id: '717', title:'야파'},
                {id: '718', title:'라포스토르 판타지'},
                {id: '719', title:'루비 피즈'},
                {id: '720', title:'레트 버틀러'},
                {id: '721', title:'아이 오브 더 허리케인'},
                {id: '722', title:'애플 프레즐'},
                {id: '723', title:'인코럽티블 샴페인'},
                {id: '724', title:'에그지트 12-E'},
                {id: '725', title:'에그 크림'},
                {id: '726', title:'엔젤 스페셜'},
                {id: '727', title:'카메하메하 펀치'},
                {id: '728', title:'캐서린 블로섬'},
                {id: '729', title:'쿨 콜린스'},
                {id: '730', title:'크란베리 크림 칵테일'},
                {id: '731', title:'그린 서머 쿨러'},
                {id: '732', title:'콰이어트 패션'},
                {id: '733', title:'케이프 코드 선라이즈'},
                {id: '734', title:'캔투미'},
                {id: '735', title:'코코 오코'},
                {id: '736', title:'코코 콜라'},
                {id: '737', title:'코코넛 쿨러'},
                {id: '738', title:'서머 쿨러'},
                {id: '739', title:'서머 딜라이트'},
                {id: '740', title:'살라토가 쿨러'},
                {id: '741', title:'산드리용'},
                {id: '742', title:'셜리 템플'},
                {id: '743', title:'잭스 스페셜'},
                {id: '744', title:'쟈니 쥴렙'},
                {id: '745', title:'스윙거'},
                {id: '746', title:'스키 와서'},
                {id: '747', title:'스포츠맨'},
                {id: '748', title:'세이프 섹스 온 더 비치'},
                {id: '749', title:'다니엘스 칵테일'},
                {id: '750', title:'더미 데이지'},
                {id: '751', title:'트로피칼 스톰'},
                {id: '752', title:'통가'},
                {id: '753', title:'너티 콜라'},
                {id: '754', title:'버진 맨해튼'},
                {id: '755', title:'버진 메리'},
                {id: '756', title:'파슨스 스페셜'},
                {id: '757', title:'퍼플 피플 이터'},
                {id: '758', title:'허니문'},
                {id: '759', title:'바르바렐라'},
                {id: '760', title:'비치코머'},
                {id: '761', title:'피치 멜바'},
                {id: '762', title:'포 키르'},
                {id: '763', title:'푸시 캣'},
                {id: '764', title:'푸시 푸트'},
                {id: '765', title:'블랑 벡 민트'},
                {id: '766', title:'프루트 컵'},
                {id: '767', title:'헤븐리 데이즈'},
                {id: '768', title:'머메이드스 송'},
                {id: '769', title:'먼디스 큐어'},
                {id: '770', title:'레드 솜브레로'},
                {id: '771', title:'레드 와인 샌드 가프'},
                {id: '772', title:'살구&그레이프 프루트 비어'},
                {id: '773', title:'카시스 크란베리 비어'},
                {id: '774', title:'칼피스 비어'},
                {id: '775', title:'캄파리 비어'},
                {id: '776', title:'샌디 가프'},
                {id: '777', title:'서브마리노'},
                {id: '778', title:'진저 비어'},
                {id: '779', title:'스톤 헤드'},
                {id: '780', title:'스트로베리 비어'},
                {id: '781', title:'데프스 차이'},
                {id: '782', title:'도그스 노즈'},
                {id: '783', title:'파나세'},
                {id: '784', title:'바나나 비어'},
                {id: '785', title:'비어 버스터'},
                {id: '786', title:'비어 풀립'},
                {id: '787', title:'비어 스프리처'},
                {id: '788', title:'피치 비어'},
                {id: '789', title:'블랙 벨벳'},
                {id: '790', title:'프랑젤리코 파인 비어'},
                {id: '791', title:'프랑부아즈 비어'},
                {id: '792', title:'블루 비어'},
                {id: '793', title:'보일러메이커'},
                {id: '794', title:'말차 비어'},
                {id: '795', title:'마린 스노'},
                {id: '796', title:'민트 비어'},
                {id: '797', title:'모카 쿠로나마'},
                {id: '798', title:'요슈'},
                {id: '799', title:'애플 비어'},
                {id: '800', title:'레드 아이'},

        ]}  
      />
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#fff",
    },
    background:{
        marginTop: 10,
        height:220,
    },
    centercontainer:{
        marginTop: 15,
        justifyContent: 'center',
        alignItems: 'center',
    },
    detailtext: {
        flex: 1,
        alignItems:"center",
        textAlign: "center",
    },
    backButton: {
        size: 16,
        // marginTop: 50,
        marginLeft: 10,
    },
    cocktailGlass: {
        marginTop: 10,
        width: 200, 
        height: 190,
    },
    titletext:{
        marginBottom: 10,
        fontSize: 20,
        fontWeight: 'bold',
    },
    subtext:{
        marginTop:25, 
        marginLeft:20,
        fontSize: 18,
        fontWeight: 'bold',
    },
    text:{ 
        marginTop:5, 
        marginLeft:20,
        marginRight:20,
        fontSize: 18,
    }
});
